package com.carbonfootprint.platform.activity.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.With;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.HashMap;
import java.util.Map;

/**
 * Core domain entity representing a real-world carbon-generating event.
 *
 * <h3>Design Principles</h3>
 * <ul>
 *   <li>Contains ONLY factual, normalised information about the event.</li>
 *   <li>Does NOT contain calculated values (carbonKg, emissionFactor).
 *       Those belong to {@link com.carbonfootprint.platform.carbon.model.CarbonAssessment}.</li>
 *   <li>Does NOT embed raw OCR text or original document bytes.
 *       Those belong to {@link com.carbonfootprint.platform.document.model.RawDocument}
 *       and are referenced by {@code rawDocumentId}.</li>
 *   <li>Is source-agnostic: the same entity model covers RECEIPT, GMAIL, SMS,
 *       BANK_STATEMENT, IOT, and MANUAL sources.</li>
 *   <li>Uses {@code metadata} for extensible, source-specific attributes so the
 *       core schema remains stable as new sources are introduced.</li>
 * </ul>
 *
 * <h3>Immutability</h3>
 * Instances are effectively immutable after construction. Use {@code @With}
 * for producing modified copies in the normalisation pipeline.
 */
@Getter
@Builder
@With
@NoArgsConstructor
@AllArgsConstructor
public class Activity {

    /**
     * Globally unique identifier (UUID v4).
     * Generated by {@link com.carbonfootprint.platform.shared.util.IdGenerator}.
     */
    private String id;

    /**
     * Document schema version for forward-compatible Firestore migrations.
     * Increment this when the persisted structure changes in a breaking way.
     * Readers must handle older schema versions gracefully.
     *
     * <p>Current version: {@code 1}
     */
    @Builder.Default
    private int schemaVersion = 1;

    /**
     * Identifier of the authenticated user who owns this activity.
     * Sourced from the Google OAuth 2.0 token subject claim.
     */
    private String userId;

    /**
     * Channel through which this activity was ingested.
     * Never null — defaults to {@link ActivitySource#UNKNOWN} if indeterminate.
     */
    private ActivitySource source;

    /**
     * High-level carbon category of the activity.
     * Never null — defaults to {@link ActivityCategory#OTHER} if indeterminate.
     */
    private ActivityCategory category;

    /**
     * Normalised merchant or vendor name.
     * Example: "Shell", "Starbucks", "British Airways".
     * Null when not applicable (e.g., electricity direct-debit).
     */
    private String merchant;

    /**
     * Monetary transaction amount associated with the activity.
     * May be null for non-monetary inputs (e.g., smart meter kWh readings).
     */
    private BigDecimal amount;

    /**
     * ISO 4217 currency code (e.g., "INR", "USD", "EUR").
     * Normalised by {@link com.carbonfootprint.platform.ingestion.normalization.impl.CurrencyNormalizer}.
     */
    private String currency;

    /**
     * Physical quantity unit (e.g., "kWh", "litres", "kg", "km").
     * Normalised by {@link com.carbonfootprint.platform.ingestion.normalization.impl.UnitNormalizer}.
     */
    private String unit;

    /**
     * Optional geographic location associated with the activity.
     * Example: city name, ISO 3166-1 alpha-2 country code, or coordinates.
     */
    private String location;

    /**
     * Timestamp of when the real-world event occurred (not ingestion time).
     * Normalised to UTC by {@link com.carbonfootprint.platform.ingestion.normalization.impl.DateNormalizer}.
     */
    private Instant occurredAt;

    /**
     * Human-readable description of the activity.
     * Derived from the document parser output.
     */
    private String description;

    /**
     * Reference to the {@link com.carbonfootprint.platform.document.model.RawDocument}
     * from which this activity was extracted. Enables audit trails and reprocessing.
     * Null for MANUAL source activities.
     */
    private String rawDocumentId;

    /**
     * Flexible key-value store for source-specific or category-specific attributes.
     *
     * <p>Examples:
     * <ul>
     *   <li>ELECTRICITY: {@code {"tariff": "peak", "meterReading": 12345}}</li>
     *   <li>FLIGHT: {@code {"origin": "BOM", "destination": "LHR", "cabin": "economy"}}</li>
     *   <li>FUEL: {@code {"fuelType": "petrol", "litres": 40.5}}</li>
     * </ul>
     *
     * <p>Schema changes to individual source types do NOT require Activity model changes.
     */
    @Builder.Default
    private Map<String, Object> metadata = new HashMap<>();

    /** Timestamp when this activity record was created in the system. */
    private Instant createdAt;

    /** Timestamp of the last update (used for optimistic concurrency). */
    private Instant updatedAt;
}
