package com.carbonfootprint.platform.mobile.model;

import lombok.Builder;
import lombok.Data;

import java.time.Instant;

/**
 * Represents a short-lived pairing code generated by an authenticated user.
 */
@Data
@Builder
public class PairingCode {
    private String code;
    private String userId;
    private Instant expiresAt;
    
    public boolean isExpired() {
        return Instant.now().isAfter(expiresAt);
    }
}
